version: '3.4'

volumes:
  database:

services:
  sample:
    image: bitnami/node-example:0.0.1
    ports:
        - 3000:3000
#  app:
#    image: akka-http-realworld-example-docker:0.1.0
#    restart: always
#    depends_on:
#      - db
#    environment:
#      DB_HOST_ENV: "host.docker.internal"
#      DB_PORT_ENV: 5555
#      DB_DB_ENV: "real_world_dev"
#      DB_USER_ENV: "postgres"
#      DB_PASS_ENV: "postgres"
#    ports:
#      - "127.0.0.1:9000:9000"
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: real_world_dev
#    ports:
#      - "5555:5432"
#    volumes:
#      - database:/var/lib/postgresql/data


